site_name: BetterSabers
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  palette:
    scheme: slate
    primary: deep purple
    accent: indigo
  font:
    text: Poppins
  features:
    - navigation.expand
    - content.code.annotate
  icon:
    repo: octicons/download-24
  custom_dir: overrides
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
plugins:
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
       - no-lb
      auto_caption: false
      caption_position: bottom
  - mkdocs-video
extra:
  generator: false
  analytics:
    provider: google 
    property: G-XNV99W0638 
  social:
    - icon: simple/kofi  
      link: https://ko-fi.com/dyvinia 
      name: Donate
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/extra.js

repo_url: https://www.nexusmods.com/starwarsbattlefront22017/mods/16 
repo_name: Download
  
copyright: Copyright &copy; Dyvinia 

nav:
  - Overview: 'index.md'
  - Tutorials:
    - Setup & Installation: 'tutorials/installation.md'
    - Creating Presets: 'tutorials/presets.md'
    - Preset Packs: 'tutorials/packs.md'
  - Recommendations: 'recommendations.md'
  - Changelog: 'changelog.md'